name: Publish Backend

on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@v0.1.7
        env:
          PM2:

        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: 22

          script: |
            source ~/.bashrc

            cd /tictactoe/backend/Tictactoe
            git pull

            $PM2 stop tictactoe

            ~/.dotnet/dotnet publish

            $PM2 start tictactoe
